name: Update README with new write-ups
on:
  push:
    paths:
      - 'Resources/Personal/Write-ups/**'
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Run updater script
        run: |
          pip install --upgrade pip
          python -m pip install requests  # or any other packages you need
          python update_writeups.py
        env:
          # This token is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
